services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=chargerReserv'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mysql-data: