spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chargerReserv?serverTimezone=Asia/Seoul
    username: root
    password: root

  profiles:
    include: API-KEY

  jpa:
    hibernate:
      ddl-auto: create
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jwt:
    secret:
      key: greenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonTgreenlemonT

  kakao:
    auth:
      client_id: 9e51411adb4b38a50e02cea1b32383fc
      redirect_uri: http://localhost:8080/auth/login
